name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer

    steps:
    - uses: actions/checkout@v3

    - name: Build APK
      run: |
        buildozer android debug
      env:
        BUILD_ALLOW_ROOT: 1

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: grind-apk
        path: bin/*.apk
